# Generated by Django 2.1.1 on 2019-07-08 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogposts', '0002_blogpost_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
