# Generated by Django 2.1.1 on 2019-07-09 07:56

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogposts', '0003_blogpost_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
