# Generated by Django 2.1.1 on 2019-07-09 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogposts', '0004_blogpost_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='next_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next', to='blogposts.blogPost'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='previous_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous', to='blogposts.blogPost'),
        ),
    ]
