# Generated by Django 2.1.1 on 2019-07-09 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogposts', '0008_auto_20190709_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='user',
            field=models.CharField(default='anonymous', max_length=50),
        ),
    ]
