# Generated by Django 2.1.1 on 2019-07-09 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogposts', '0010_auto_20190709_1632'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
    ]
