# Generated by Django 2.1.1 on 2019-07-09 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogposts', '0011_delete_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='profile_picture',
            field=models.ImageField(default=True, upload_to=''),
            preserve_default=False,
        ),
    ]
